name: BENCHMARK-SUBSTRATE
on:
  workflow_dispatch:
    inputs:
      benchmark-time:
        description: 'Benchmark time'
        default: 30
        require: true
      indexerVersion:
        description: 'indexer version'
        default: 'latest'
        require: true
      deployment:
        description: 'Deployment'
        default: 'QmakYyTWzTxaDU842CczyDWV51Ay9E55k7kbRRXTB3f395'
        require: false
      network-endpoint:
        description: 'Network endpoint'
        default: 'wss://rpc-polkadot.luckyfriday.io'
        require: true
      disableHistorical:
        description: 'Disable historical'
        default: 'true'
        require: false
      batch-size:
        description: 'batch-size'
        default: 30
        require: false
      workers:
        description: 'workers'
        default: 4
        require: false
      others:
        description: 'Other flags'
        require: false

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    continue-on-error: true
    # Docker Hub image that `container-job` executes in
    container: node:18

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:12-alpine
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      #Check out
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      # queries database with postgres client
      - name: Setup historical database
        run: psql -h postgres -d postgres -U postgres -c 'CREATE EXTENSION IF NOT EXISTS btree_gist;'
        env:
          PGPASSWORD: postgres

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i @subql/node@${{ github.event.inputs.indexerVersion }} -g

      - name: Benchmarking
        id: app
        continue-on-error: true
        run: |
          chmod +x .github/workflows/substrate.sh
          .github/workflows/substrate.sh ${{github.event.inputs.benchmark-time}} ${{ github.event.inputs.deployment }} ${{ github.event.inputs.network-endpoint }} ${{ github.event.inputs.batch-size }} ${{ github.event.inputs.workers }} ${{ github.event.inputs.disableHistorical }} ${{ github.event.inputs.others }}
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DB_USER: postgres
          DB_PASS: postgres
          DB_DATABASE: postgres
          DB_HOST: postgres
          DB_PORT: 5432

      - name: Filter Logs for 'benchmark' keyword
        run: |
          if grep -qi "benchmark" substrate/indexing.log; then
            grep -i "benchmark" substrate/indexing.log > substrate/benchmark.log
          else
            echo "No lines containing 'benchmark' found in substrate/indexing.log"
          fi

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HHMM
          utcOffset: "+12:00"

      - name: Config git
        run: git config --global --add safe.directory /__w/auction/auction
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          message: Benchmark_Report_${{steps.current-time.outputs.formattedTime}}_${{ github.event.inputs.indexerVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

